### PR TITLE
Feature/support https

### PR DESCRIPTION
**Pull request by amanica**
hi, 
I'd like to use this library to connect to influxdb cloud,  but for that I need https support, so I gave that a go.
In order to be backwards compatible but still allow configuring an https url, I suggest we move away from INFLUXDB_HOST to INFLUXDB_URL

I also fixed some bugs I ran into while testing this
* support influx org names that contain a space, by converting it to "%20"
* in query.jl line 57 I filter out lines where _time=_time apparently influx is happy to repeat headers:
Selection_528

Let me know if you need me to change anything.

### CODE REVIEW

**Comment by amanica** [comment]
I don't think this github ci pipeline is configured correctly, hence the pipeline is failing: https://stackoverflow.com/a/67998780/381083
with my changes, it should be possible to test agains a influx cloud db

**Comment by kafisatz** [comment]
> I don't think this github ci pipeline is configured correctly, hence the pipeline is failing: https://stackoverflow.com/a/67998780/381083 with my changes, it should be possible to test agains a influx cloud db

I am not sure why the CI is not working. Clearly it used to work a month ago: https://github.com/kafisatz/InfluxDBClient.jl/actions/runs/3845052229/jobs/6548750295

**Comment by kafisatz** [comment]
> > I don't think this github ci pipeline is configured correctly, hence the pipeline is failing: https://stackoverflow.com/a/67998780/381083 with my changes, it should be possible to test agains a influx cloud db
> 
> I am not sure why the CI is not working. Clearly it used to work a month ago: https://github.com/kafisatz/InfluxDBClient.jl/actions/runs/3845052229/jobs/6548750295

@amanica  I fixed the CI. It seems that it is working with InfluxDB 2.4, but 'latest' (2.6?) does not seem to work. Might be about default settings or http vs https. Notably I have not tested https (neither locally nor in CI). Also I can't test influxdb cloud.

**Comment by amanica** [comment]
thanks for sorting out and merging!

**Pull request merged**
