### PR TITLE
Feature/support range start with stop

### PR DESCRIPTION
**Pull request by amanica**
hi, 
I picked up a bug while trying to specify a stop value when querying eg:

    df2 = query_flux(isettings,a_random_bucket_name,"my_meas";tzstr = "Europe/Berlin",range=Dict("start"=>adt, **"stop"=>adt+Minute(21)**),fields=["temperature","humidity"],tags=Dict("color"=>"blue"),aggregate=agg);

I finally managed to run the tests after some struggles. To make it easier for the next guy, I added info in the `README.md`, feel free to correct/improve it.

thanks

### CODE REVIEW

**Comment by amanica** [comment]
@kafisatz  I don't know why the build checks are failing for me - I don't know the server setup, but it can't seem to connect to influx on localhost, and I don't think I changed anything there. Let me know if there is something I can fix..
image

**Comment by kafisatz** [comment]
thanks.
tests pass on my computer. Not sure why they don't pass on CI
seems to be related to o```    metrics_url = """http://$(isettings["INFLUXDB_HOST"])/metrics"""```

**Comment by kafisatz** [comment]
@amanica  regarding tests you wrote 
"But in order to run runtests.jl or individual tests manually you need to activate the test dependencies, and since this is still has Julia 1 compatibility, we need to use the following method:"

I could drop support for 1.0 and keep only 1.8 support. Would that help?

**Comment by amanica** [comment]
> @amanica regarding tests you wrote "But in order to run runtests.jl or individual tests manually you need to activate the test dependencies, and since this is still has Julia 1 compatibility, we need to use the following method:"
> 
> I could drop support for 1.0 and keep only 1.8 support. Would that help?

I think it would be good to support the latest LTS: 1.6 and that will help with being able to switch environments easily for local testing. Since I found a workaround I don't mind too much - I assumed you had a reason to support version 1.
I was forced to upgrade to 1.8 in the project that I use this in (as a result of other packages I use).

**Comment by kafisatz** [comment]
done 
https://github.com/kafisatz/InfluxDBClient.jl/blob/20319a8f3c22bb1bdd14f36c809075f60b986752/Project.toml#L18

**Pull request merged**
